### ISSUE TITLE
Not imlpemented methods of Authorizer

### ISSUE THREAD

**Issue by iamatwork** [anderseknert/opa-kafka-plugin#25]
Some methods of the Authorizer are not imlpemented by OpaAuthorizer, but are called by Kafka under certain circumstances:
Write to a topic with ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG=true, but no transactional_id produces multiple requests to OPA:
* DESCRIBE TOPIC "mytopic" (granted by my rules)
* IDEMPOTENT_WRITE CLUSTER, which is denied by my rules.
* WRITE TOPIC "hardcode" This comes from Kafka's authorizeByResourceType(..) at Authorizer.java:182. which is called by KafkaApis.scala:2131 in case the previous request was denied. 

This leads to multiple reties by the client, and exceptions in Kafka's log.

The comment at Authorizer.authorizeByResourceType(..) states "check if the caller is authorized to perform the given ACL operation on at least one resource of the given type". 
A quick fix might be to implement the remaining methods to return an empty collection.

I tried to implement a better solution, which maps Authorizer.authorizeByResourceType to a call to OPA with PatternType.PREFIX, resource.name="". So OPA can take the decision like AclAuthorizer would.
https://github.com/iamatwork/opa-kafka-plugin/tree/imlpement-authorize-by-resource-type

`ERROR kafka.server.KafkaApis - [KafkaApi-3] Unexpected error handling request RequestHeader(apiKey=INIT_PRODUCER_ID, apiVersion=4, clientId=kafka-opa-decisionlog-test-on-lm-98b61dc9-b098-409d-9583-08aa5650f0ce-write-idemPotent-, correlationId=2) -- InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1) with context RequestContext(header=RequestHeader(apiKey=INIT_PRODUCER_ID, apiVersion=4, clientId=kafka-opa-decisionlog-test-on-lm-98b61dc9-b098-409d-9583-08aa5650f0ce-write-idemPotent-, correlationId=2), connectionId='10.30.7.136:9092-10.21.72.98:50773-349', clientAddress=/10.21.72.98, principal=User:XXXXX, listenerName=ListenerName(OUTSIDE), securityProtocol=SSL, clientInformation=ClientInformation(softwareName=apache-kafka-java, softwareVersion=3.0.0), fromPrivilegedListener=false, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@6f9751a0])
scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
        at com.bisnode.kafka.authorization.OpaAuthorizer.acls(OpaAuthorizer.scala:68)
        at org.apache.kafka.server.authorizer.Authorizer.authorizeByResourceType(Authorizer.java:213)
        at com.bisnode.kafka.authorization.OpaAuthorizer.authorizeByResourceType(OpaAuthorizer.scala:34)
        at kafka.server.AuthHelper.$anonfun$authorizeByResourceType$1(AuthHelper.scala:77)
        at kafka.server.AuthHelper.$anonfun$authorizeByResourceType$1$adapted(AuthHelper.scala:76)
        at scala.Option.forall(Option.scala:420)
        at kafka.server.AuthHelper.authorizeByResourceType(AuthHelper.scala:76)
        at kafka.server.KafkaApis.handleInitProducerIdRequest(KafkaApis.scala:2131)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:191)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:75)
        at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by anderseknert** [comment]
Hi Lukas! Thanks for reporting this. Is the trace you provided from before or after you applied your fix? Would you consider opening a PR?

**Comment by iamatwork** [comment]
Hi Anders,

the stack trace was before the fix. Will open a PR soon.

**Comment by iamatwork** [comment]
I added a little bit of documentation in the PR (https://github.com/anderseknert/opa-kafka-plugin/pull/26)
And checked Kafka's source for other uses of authorizeByResourceType, but couldn't find any.
Everything seems to work fine with my test-cluster.

**Comment by anderseknert** [comment]
Resolved with #26
