### ISSUE TITLE
Export metrics for Authorizer

### ISSUE THREAD

**Issue by quangminhtran94** [anderseknert/opa-kafka-plugin#37]
Currently, there are no metrics related to authorization recorded. Therefore, it is hard to keep track of how authorizer is doing. I propose some metrics should be recorded here:
- Number of authorized/unauthorized requests: This can be useful to check if there is any abnormal number of unauthorized request coming to our cluster
- Cache hit rate: This can be useful to tune cache configuration such as expiration time
- Cache capacity usage: Because caching is very important for performance

Slack discussion: https://cloud-native.slack.com/archives/CMH3Q3SNP/p1641481042006600

**Comment by quangminhtran94** [comment]
Hi team,
I have done some work related to this, but I cannot push my code to feature branch because I don't have permission. Can anyone give me permission to push to feature branch please? Thank you!

**Comment by anderseknert** [comment]
Sounds exciting 😃 The way you prepare a PR against a project is normally by first forking it, then submitting the PR from a branch in your fork.

**Comment by quangminhtran94** [comment]
> Sounds exciting 😃 The way you prepare a PR against a project is normally by first forking it, then submitting the PR from a branch in your fork.

Thank you! I have created PR mentioned above.
Please give any comment, really appreciate!

**Comment by anderseknert** [comment]
Resolved in https://github.com/anderseknert/opa-kafka-plugin/pull/38
